name: Waka Readme

on:
  workflow_dispatch: # Allows you to run the workflow manually
  schedule:
    # Runs at 12 AM UTC every day
    - cron: '0 0 * * *'

jobs:
  update-readme:
    name: Update README with WakaTime stats
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: true
          TIME_RANGE: last_7_days # Options: last_7_days, last_30_days, last_6_months, last_year, all_time
          SHOW_TIME: true
